### ISSUE TITLE
googleCloudStorageR

### ISSUE THREAD

**Issue by fncalderong** [cloudyr/cloudyr.github.io#15]
Hi, I am using googleCloudStorageRs package. I am trying to download a 2gb txt file with R but have no susses.

I tried to download the file with gcs_get_object function, but the file is in Raw format and is quite dificult to convert it. 

I tried to get the URL of the file with gcs_download_url function, but when I try to download the file via URL using downloadFile from R.utils Package it download a html file (the page where google ask the credentials).

**Comment by leeper** [comment]
Probably better to report here: https://github.com/cloudyr/googleCloudStorageR cc @MarkEdmondson1234

**Comment by MarkEdmondson1234** [comment]
Yes best report there, but it sounds like you only need to specify the `.txt` file extension in the name you have downloaded it to.  Try renaming the file.

**Comment by fncalderong** [comment]
when I try to run this:

gcs_get_object(objects$name[[36]], saveToDisk = "data.txt",bucket)

I get this:

Error in writeBin(bin, saveToDisk) :
  long vectors not supported yet: connections.c:4123

where

> objects$name[[36]][1] "20170523/planofull_170523.txt"

thanks


2017-05-24 17:12 GMT-05:00 Mark <notifications@github.com>:
