### ISSUE TITLE
Azure packages

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/cloudyr.github.io#17]
Hi all,

I'm in the process of putting together a set of packages for interfacing with Azure. Would you be interested in having them as part of CloudyR?

It's just early days yet, so there's only 3 packages and they're still pretty much in the beta testing stage. You can see the work so far here:

- [hong-revo/AzureRMR](https://github.com/hong-revo/AzureRMR): base package for working with subscriptions, resource groups, templates and resources via Azure Resource Manager. Uses R6 exclusively.

- [hong-revo/AzureVM](https://github.com/hong-revo/AzureVM): sample package for spinning up and deleting virtual machines. Extends AzureRMR classes.

- [hong-revo/AzureStor](https://github.com/hong-revo/AzureStor): package for working with Azure Storage, extends AzureRMR. Provides both an admin/owner interface for managing storage accounts, and a client interface for uploading/downloading data.

Looking through your [style guidelines](http://cloudyr.github.io/styleguide/), I think I hit most of them. The only major changes is are curly-braces for all if-else statements, and reading default connection parameters from an environment variable rather than via `options()`.

**Comment by leeper** [comment]
Definitely! Would be very glad to have these as part of the suite. Let me know if you're still interested.

**Comment by Hong-Revo** [comment]
Hi! Yes, still interested. The packages are still a bit rough around the edges. Also, I have one for AKS (Kubernetes) in the works. Can I polish them up before moving them over?

**Comment by leeper** [comment]
Absolutely. Totally up to you. I'll put you on an "azure" team here and then we can go from there.

**Comment by Hong-Revo** [comment]
Quick update: on the technical side, things should be working now. I'm also in the process of putting together a package for containers (Azure Container Registry and Kubernetes Service), which will probably take a few more weeks to make ready.

Internally though, I've been told that I should probably run this via Legal first. I don't anticipate any hiccups, but it'll just be a bit longer.

**Comment by Hong-Revo** [comment]
Got out of the meeting with Legal, and they had one question: do you have any policy on licensing?

If not, it it okay to release my Azure stuff under the MIT license?

**Comment by leeper** [comment]
Yep, that's fine

**Comment by Hong-Revo** [comment]
Ok, thanks guys. I don't think there's any other major obstacles, just need to get some signoffs.

I have another package basically completed: https://github.com/hong-revo/AzureContainers for working with Azure Container Registry, Container Instances and Kubernetes Service. Assuming everything works out, I'll be looking to port all 4 packages over.

**Comment by Hong-Revo** [comment]
Sorry for the delay, but I've finally got the go-ahead to put this on CloudyR!

What do I need to do to make this happen?

**Comment by MarkEdmondson1234** [comment]
Hi @Hong-Revo I can see you have an invite to join https://github.com/cloudyr so if you accept that, you should then have access to an Azure team made for you.  Then there is a package repo template you can review here: https://github.com/cloudyr/pkgtemplate and you should be able to migrate your current GitHub repos over to the cloudyr organisation.  

There may be some other steps around travis and building to add your packages to the drat repo, but that will get you started I hope.  @leeper is on a hiatus at the moment I believe.

**Comment by Hong-Revo** [comment]
Thanks, I'd forgotten about that invite. Looking at the template now, I assume the bits about AWS are not relevant to me, and can be replaced by an equivalent blurb about Azure?

**Comment by MarkEdmondson1234** [comment]
Yep, replace as you need.

**Comment by Hong-Revo** [comment]
Just tried to migrate my AzureRMR package, but I don't have authority to create repos in CloudyR.

**Comment by MarkEdmondson1234** [comment]
Can you try now?

**Comment by Hong-Revo** [comment]
Sweet, all done! You should be able to access them:

https://github.com/cloudyr/AzureRMR
https://github.com/cloudyr/AzureVM
https://github.com/cloudyr/AzureStor
https://github.com/cloudyr/AzureContainers

Just need to tweak them to fully conform to the style guidelines, specifically putting braces around all if-else statements.

**Comment by MarkEdmondson1234** [comment]
Very awesome, thanks very much.  I'm just using Azure seriously this week too so good timing :)

**Comment by Hong-Revo** [comment]
@MarkEdmondson1234 I'm trying to enable Travis on my packages. Could I get you (or another CloudyR owner) to approve the access request? Thanks!

**Comment by MarkEdmondson1234** [comment]
Hi @Hong-Revo - I approved access - we had Travis already approved but for Open source, so the approved Travis was for private repos I think?

**Comment by MarkEdmondson1234** [comment]
@Hong-Revo when you are ready, lets announce and publicise the new packages

**Comment by Hong-Revo** [comment]
Yeah, I'm not sure what happened... never had to deal with activating Travis on a separate org before. I think I may have just kicked off another request actually.

We're almost good for an announcement. Just making some final checks.
