### ISSUE TITLE
New package, adding a team member

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/cloudyr.github.io#22]
@MarkEdmondson1234  what is the proper procedure for adding someone to a repo? I've created [cloudyr/AzureDataExplorer](../../AzureDataExplorer) for an interface to this Azure service, and I'd like to add @alexkyllo. I noticed I'm an owner of the repo, can I just add him as a collaborator?

**Comment by MarkEdmondson1234** [comment]
Yes sure you have control.

**Comment by Hong-Revo** [comment]
Ok, thanks. I've added Alex, but apparently he can't push changes to the repo. According to the settings panel, he should have write access though:

![image](https://user-images.githubusercontent.com/11328890/49819074-903cf280-fdc8-11e8-8a13-c6847b9750ec.png)

Does he need to be a member of the cloudyr org as well?
