### ISSUE TITLE
Add AzureGraph and AzureKeyVault to Travis

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/cloudyr.github.io#31]
@MarkEdmondson1234 could you add these packages to the Travis org? I don't have the permissions to do so myself.

**Comment by MarkEdmondson1234** [comment]
I have done this!  Please check it

**Comment by Hong-Revo** [comment]
Yup, it works. Thanks! Btw, I have a PR for my latest Azure update open as well.
