### ISSUE TITLE
Moving/copying Azure packages to Azure org

### ISSUE THREAD

**Issue by Hong-Revo** [cloudyr/cloudyr.github.io#34]
Hi @MarkEdmondson1234,

The Azure packages I've been writing have caught the attention of the higher-ups in my team at MS. They want to make it "official", ie, move them into the Azure organisation. However, rather than orphan cloudyr, it was suggested that we could setup the packages to be mirrored here, via an Azure Pipeline or something similar. Would this be acceptable?

**Comment by MarkEdmondson1234** [comment]
That sounds great, congratulations! Yes a pipeline to duplicate to help aid discovery would be great if that’s ok with you.


________________________________

**Comment by Hong-Revo** [comment]
I've setup AzureAuth to be copied from https://github.com/Azure/AzureAuth. If this looks ok, I'll do the rest.

**Comment by Hong-Revo** [comment]
All Azure packages have now been copied over. I'll get the drat auto-update fixed up as well.

**Comment by Hong-Revo** [comment]
Hmm, the drat repo seems to have updated successfully, but I got an error:

> The page build failed for the `master` branch with the following error:
>
> Page build failed. For more information, see https://help.github.com/en/articles/troubleshooting-github-pages-builds

**Comment by Hong-Revo** [comment]
Nope, it didn't take. The push to the master branch succeeded, but the cloudyr.github.io/drat repo still contains the old build.

**Comment by Hong-Revo** [comment]
Now fixed, I had to remove the git `user.email` and `user.name` options in drat.sh.
