### ISSUE TITLE
Update GA tracking?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [cloudyr/cloudyr.github.io#7]
I have Google Tag Manager on my websites with Google Analytics enabled, which is more flexible than hard coding it within the page - could we migrate all the pages to it?  We can keep your GA account and historic data.  If I could be added to your GA account I can sort it, my email to add is me [at] markedmondson . me

**Comment by MarkEdmondson1234** [comment]
Ok, looks to be working now.  I gave your gmail access to Google Tag Manager here: https://tagmanager.google.com/#/container/accounts/333162484/containers/2325394

If tags ever need changing or adding to, thats the place.

**Comment by leeper** [comment]
Thank you!
